### ISSUE TITLE
Analytics link on an item results in "Something went wrong" page

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/gw-sufia#140]

**Comment by kilahimm** [comment]
I, [2015-04-16T09:47:55.111227 #17672]  INFO -- : Started GET "/downloads/qj72p7427?datastream_id=thumbnail" for 128.164.213.87 at 2015-04-16 09:47:55 -0400
I, [2015-04-16T09:47:55.117304 #17672]  INFO -- : Processing by DownloadsController#show as HTML
I, [2015-04-16T09:47:55.117454 #17672]  INFO -- :   Parameters: {"datastream_id"=>"thumbnail", "id"=>"qj72p7427"}
I, [2015-04-16T09:47:55.159218 #17672]  INFO -- : Completed 200 OK in 42ms (ActiveRecord: 5.3ms)
I, [2015-04-16T09:47:56.745864 #17672]  INFO -- : Started GET "/files/qj72p7427/stats" for 128.164.213.87 at 2015-04-16 09:47:56 -0400
I, [2015-04-16T09:47:56.752005 #17672]  INFO -- : Processing by GenericFilesController#stats as HTML
I, [2015-04-16T09:47:56.752146 #17672]  INFO -- :   Parameters: {"id"=>"qj72p7427"}
I, [2015-04-16T09:47:57.667957 #17672]  INFO -- : Completed 500 Internal Server Error in 916ms
F, [2015-04-16T09:47:57.672979 #17672] FATAL -- :
NoMethodError (undefined method `year' for nil:NilClass):
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/values/time_zone.rb:288:in `parse'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/core_ext/string/zones.rb:8:in `in_time_zone'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/attribute_methods/time_zone_conversion.rb:37:in `date='
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/attribute_assignment.rb:42:in `public_send'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/attribute_assignment.rb:29:in `block in assign_attributes'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/attribute_assignment.rb:23:in `each'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/attribute_assignment.rb:23:in `assign_attributes'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/core.rb:468:in `init_attributes'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/core.rb:185:in `initialize'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/inheritance.rb:30:in `new'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/inheritance.rb:30:in `new'
  vendor/bundle/ruby/2.2.0/gems/sufia-models-4.2.0/app/models/concerns/sufia/file_stat_utils.rb:26:in `block in combined_stats'
  vendor/bundle/ruby/2.2.0/gems/legato-0.4.0/lib/legato/query.rb:156:in `each'
  vendor/bundle/ruby/2.2.0/gems/legato-0.4.0/lib/legato/query.rb:156:in `each'
  vendor/bundle/ruby/2.2.0/gems/sufia-models-4.2.0/app/models/concerns/sufia/file_stat_utils.rb:25:in `combined_stats'
  vendor/bundle/ruby/2.2.0/gems/sufia-models-4.2.0/app/models/file_download_stat.rb:9:in `statistics'
  vendor/bundle/ruby/2.2.0/gems/sufia-models-4.2.0/app/models/file_usage.rb:11:in `initialize'
  vendor/bundle/ruby/2.2.0/gems/sufia-4.2.0/app/controllers/concerns/sufia/files_controller_behavior.rb:59:in `new'
  vendor/bundle/ruby/2.2.0/gems/sufia-4.2.0/app/controllers/concerns/sufia/files_controller_behavior.rb:59:in `stats'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/abstract_controller/base.rb:189:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/callbacks.rb:473:in `_run__2328499950232183486__process_action__callbacks'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/callbacks.rb:80:in `run_callbacks'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/notifications.rb:159:in `block in instrument'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/notifications.rb:159:in `instrument'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/abstract_controller/base.rb:136:in `process'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/abstract_controller/rendering.rb:44:in `process'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_controller/metal.rb:195:in `dispatch'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_controller/metal.rb:231:in `block in action'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/routing/route_set.rb:80:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/routing/route_set.rb:48:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/journey/router.rb:71:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/journey/router.rb:59:in `each'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/journey/router.rb:59:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/routing/route_set.rb:674:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.0.5/lib/rails/engine.rb:511:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.0.5/lib/rails/railtie/configurable.rb:30:in `method_missing'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/journey/router.rb:71:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/journey/router.rb:59:in `each'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/journey/router.rb:59:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/routing/route_set.rb:674:in `call'
  vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  vendor/bundle/ruby/2.2.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
  vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/middleware/flash.rb:241:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/middleware/cookies.rb:486:in `call'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.0.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/callbacks.rb:373:in `_run__3736498499252944070__call__callbacks'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/callbacks.rb:80:in `run_callbacks'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.0.5/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.2.0/gems/railties-4.0.5/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.2.0/gems/railties-4.0.5/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.2.0/gems/actionpack-4.0.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.5/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.0.5/lib/rails/engine.rb:511:in `call'
  vendor/bundle/ruby/2.2.0/gems/railties-4.0.5/lib/rails/application.rb:97:in `call'
  /home/mihalik/.rvm/gems/ruby-2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /home/mihalik/.rvm/gems/ruby-2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /home/mihalik/.rvm/gems/ruby-2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /home/mihalik/.rvm/gems/ruby-2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

**Comment by kilahimm** [comment]
Starting to wonder if this is a routing issue, see route.rb in 4.3 sufia: https://github.com/projecthydra/sufia/blob/4.3-stable/config/routes.rb way more complex than it was before.  Did we miss something?

**Comment by kilahimm** [comment]
Deleted earlier comment, was looking at Sufia route.rb which we inherit.  Current thought is that this is a Ruby 2.2.0 bug: https://bugs.ruby-lang.org/issues/10758
